import 'package:flutter_quill/flutter_quill.dart';
import '../../l10n/app_localizations.dart';
import 'package:flutter/material.dart';

class NoteTemplate {
  final String key;
  final String Function(AppLocalizations? l10n) name;
  final IconData icon;
  final int color;
  final String category;
  final List<dynamic> deltaJson;

  const NoteTemplate({
    required this.key,
    required this.name,
    required this.icon,
    required this.color,
    required this.category,
    required this.deltaJson,
  });

  Document toDocument() => Document.fromJson(deltaJson);
}

final List<NoteTemplate> noteTemplates = [
  NoteTemplate(
    key: 'blank',
    name: (l10n) => l10n?.noteTemplateBlank ?? 'Blank Note',
    icon: Icons.description_rounded,
    color: 0xFF6C63FF,
    category: 'general',
    deltaJson: [
      {'insert': '\n'},
    ],
  ),
  NoteTemplate(
    key: 'meeting',
    name: (l10n) => l10n?.noteTemplateMeeting ?? 'Meeting Notes',
    icon: Icons.groups_rounded,
    color: 0xFF4285F4,
    category: 'meeting',
    deltaJson: [
      {'insert': 'Meeting Notes'},
      {
        'insert': '\n',
        'attributes': {'header': 1},
      },
      {'insert': '\n'},
      {'insert': '📅 Date: '},
      {'insert': '\n'},
      {'insert': '👥 Participants: '},
      {'insert': '\n'},
      {'insert': '📍 Location: '},
      {'insert': '\n\n'},
      {'insert': 'Agenda'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Item 1'},
      {
        'insert': '\n',
        'attributes': {'list': 'ordered'},
      },
      {'insert': 'Item 2'},
      {
        'insert': '\n',
        'attributes': {'list': 'ordered'},
      },
      {'insert': '\n'},
      {'insert': 'Discussion Notes'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': '\n\n'},
      {'insert': 'Action Items'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Action item 1'},
      {
        'insert': '\n',
        'attributes': {'list': 'unchecked'},
      },
      {'insert': 'Action item 2'},
      {
        'insert': '\n',
        'attributes': {'list': 'unchecked'},
      },
      {'insert': '\n'},
      {'insert': 'Decisions'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': '\n'},
    ],
  ),
  NoteTemplate(
    key: 'diary',
    name: (l10n) => l10n?.noteTemplateDiary ?? 'Diary',
    icon: Icons.book_rounded,
    color: 0xFFFF6B6B,
    category: 'personal',
    deltaJson: [
      {'insert': 'Daily Diary'},
      {
        'insert': '\n',
        'attributes': {'header': 1},
      },
      {'insert': '\n'},
      {'insert': '🌅 Morning'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'How did the day start?\n\n'},
      {'insert': 'â˜€️ Afternoon'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Key events and feelings...\n\n'},
      {'insert': '🌙 Evening'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Reflections and gratitude...\n\n'},
      {'insert': '💡 Learned Today'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': '\n'},
      {'insert': '🎯 Goals for Tomorrow'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Goal 1'},
      {
        'insert': '\n',
        'attributes': {'list': 'unchecked'},
      },
      {'insert': '\n'},
    ],
  ),
  NoteTemplate(
    key: 'idea',
    name: (l10n) => l10n?.noteTemplateIdea ?? 'Ideas',
    icon: Icons.lightbulb_rounded,
    color: 0xFFFFB800,
    category: 'ideas',
    deltaJson: [
      {'insert': '💡 Idea'},
      {
        'insert': '\n',
        'attributes': {'header': 1},
      },
      {'insert': '\n'},
      {'insert': 'Summary'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Brief description of the idea...\n\n'},
      {'insert': 'Problem'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'What problem does this solve?\n\n'},
      {'insert': 'Solution'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'How does it work?\n\n'},
      {'insert': 'Next Steps'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Step 1'},
      {
        'insert': '\n',
        'attributes': {'list': 'unchecked'},
      },
      {'insert': 'Step 2'},
      {
        'insert': '\n',
        'attributes': {'list': 'unchecked'},
      },
      {'insert': '\n'},
    ],
  ),
  NoteTemplate(
    key: 'project',
    name: (l10n) => l10n?.noteTemplateProject ?? 'Project Plan',
    icon: Icons.folder_rounded,
    color: 0xFF00BFA5,
    category: 'work',
    deltaJson: [
      {'insert': 'Project Plan'},
      {
        'insert': '\n',
        'attributes': {'header': 1},
      },
      {'insert': '\n'},
      {'insert': 'Overview'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Project description and objectives...\n\n'},
      {'insert': 'Timeline'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Phase 1: '},
      {
        'insert': '\n',
        'attributes': {'list': 'ordered'},
      },
      {'insert': 'Phase 2: '},
      {
        'insert': '\n',
        'attributes': {'list': 'ordered'},
      },
      {'insert': 'Phase 3: '},
      {
        'insert': '\n',
        'attributes': {'list': 'ordered'},
      },
      {'insert': '\n'},
      {'insert': 'Resources'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': '\n'},
      {'insert': 'Risks & Mitigations'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': '\n'},
      {'insert': 'Success Criteria'},
      {
        'insert': '\n',
        'attributes': {'header': 2},
      },
      {'insert': 'Criteria 1'},
      {
        'insert': '\n',
        'attributes': {'list': 'unchecked'},
      },
      {'insert': '\n'},
    ],
  ),
  NoteTemplate(
    key: 'standup',
    name: (_) => 'Günlük Standup',
    icon: Icons.record_voice_over_rounded,
    color: 0xFF0097A7,
    category: 'meeting',
    deltaJson: [
      {'insert': 'Günlük Standup'},
      {'insert': '\n', 'attributes': {'header': 1}},
      {'insert': '\n'},
      {'insert': 'Dün'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': 'Neleri tamamladım?'},
      {'insert': '\n', 'attributes': {'list': 'bullet'}},
      {'insert': '\n'},
      {'insert': 'Bugün'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': 'Ne üzerinde çalışacağım?'},
      {'insert': '\n', 'attributes': {'list': 'bullet'}},
      {'insert': '\n'},
      {'insert': 'Engeller'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': 'Herhangi bir engel var mı?'},
      {'insert': '\n', 'attributes': {'list': 'bullet'}},
      {'insert': '\n'},
    ],
  ),
  NoteTemplate(
    key: 'research',
    name: (_) => 'Araştırma Notları',
    icon: Icons.science_rounded,
    color: 0xFF7B1FA2,
    category: 'work',
    deltaJson: [
      {'insert': 'Araştırma Notları'},
      {'insert': '\n', 'attributes': {'header': 1}},
      {'insert': '\n'},
      {'insert': 'Konu'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': '\n'},
      {'insert': 'Temel Sorular'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': 'Soru 1'},
      {'insert': '\n', 'attributes': {'list': 'ordered'}},
      {'insert': 'Soru 2'},
      {'insert': '\n', 'attributes': {'list': 'ordered'}},
      {'insert': '\n'},
      {'insert': 'Kaynaklar'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': 'Kaynak 1'},
      {'insert': '\n', 'attributes': {'list': 'bullet'}},
      {'insert': '\n'},
      {'insert': 'Bulgular'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': '\n'},
      {'insert': 'Sonuçlar'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': '\n'},
    ],
  ),
  NoteTemplate(
    key: 'reading',
    name: (_) => 'Okuma Notları',
    icon: Icons.menu_book_rounded,
    color: 0xFF2E7D32,
    category: 'personal',
    deltaJson: [
      {'insert': 'Okuma Notları'},
      {'insert': '\n', 'attributes': {'header': 1}},
      {'insert': '\n'},
      {'insert': '📖 Kitap / Makale: '},
      {'insert': '\n'},
      {'insert': '✍️ Yazar: '},
      {'insert': '\n'},
      {'insert': '⭐ Puan: '},
      {'insert': '\n\n'},
      {'insert': 'Önemli Çıkarımlar'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': 'Çıkarım 1'},
      {'insert': '\n', 'attributes': {'list': 'bullet'}},
      {'insert': '\n'},
      {'insert': 'Alıntılar'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': '"Dikkat çeken bir alıntı..."'},
      {'insert': '\n', 'attributes': {'blockquote': true}},
      {'insert': '\n'},
      {'insert': 'Düşüncelerim'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': '\n'},
      {'insert': 'Eylem Maddeleri'},
      {'insert': '\n', 'attributes': {'header': 2}},
      {'insert': 'Bu fikri uygula'},
      {'insert': '\n', 'attributes': {'list': 'unchecked'}},
      {'insert': '\n'},
    ],
  ),
];
