// ignore_for_file: avoid_print
//
// Scans lib/ for Icons.* references and regenerates the icon manifest used
// by the web release icon tree shaker.
//
// Run after adding new Material icons:
//   dart run tool/generate_icon_manifest.dart

import 'dart:io';

void main() {
  final libDir = Directory('lib');
  if (!libDir.existsSync()) {
    stderr.writeln('Run from project root (lib/ not found).');
    exit(1);
  }

  final pattern = RegExp(r'Icons\.(\w+)');
  final names = <String>{};

  for (final entity in libDir.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    if (entity.path.contains('material_icon_manifest')) continue;

    final text = entity.readAsStringSync();
    for (final match in pattern.allMatches(text)) {
      names.add(match.group(1)!);
    }
  }

  final sorted = names.toList()..sort();

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/generate_icon_manifest.dart — do not edit.')
    ..writeln('// ignore_for_file: constant_identifier_names')
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln()
    ..writeln('/// Every `Icons.*` used under [lib].')
    ..writeln('/// Referenced at app root so release web builds retain these glyphs.')
    ..writeln('abstract final class MaterialIconManifest {')
    ..writeln('  static const List<IconData> all = [');
  for (final name in sorted) {
    buffer.writeln('    Icons.$name,');
  }
  buffer
    ..writeln('  ];')
    ..writeln('}');

  final outFile = File('lib/core/generated/material_icon_manifest.g.dart');
  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(buffer.toString());

  print('MaterialIconManifest: ${sorted.length} icons → ${outFile.path}');
}
